var path = require('path');

var version = '0.1.0';
var date = new Date();

var configure = function(grunt) {
  grunt.initConfig({

    pkg: grunt.file.readJSON('package.json'),

    // system paths
    paths: {
      examples: path.join(__dirname, 'examples'),
      lib: path.join(__dirname, 'lib'),
    },

    // auto-generated messages
    banner: {
      css: '' +
        '/*\n' +
        ' * This file has been generated by stylus\n' +
        ' */\n',
      js: '' +
        '/*\n' +
        ' * Generic - jQuery Plugin\n' +
        ' * Simple ui controllers\n' +
        ' *\n' +
        ' * Examples and documentation at:\n' +
        ' *\n' +
        ' * Copyright (c) 2013 Dan LE VAN\n' +
        ' *\n' +
        ' * Version: ' + version + ' (' + date.toDateString() + ')\n' +
        ' * Requires: jQuery v1.3+\n' +
        ' *' +
        ' * Licensed under the MIT license:\n' +
        ' *   http://www.opensource.org/licenses/mit-license.php\n' +
        ' */\n',
    },

    // grunt-contrib-clean
    clean: {
      examples: [
        '<%= paths.examples %>',
      ],

      lib: [
        '<%= paths.lib %>',
      ]
    },

    // grunt-contrib-copy
    copy: {

      lib: {
        files: [{
          dest: '<%= paths.lib %>/',
          src: 'src/lib/jquery.genericBox.js',
          expand: true,
          flatten: true,
        }],
      },

      examples: {
        files: [{
          cwd: 'src/examples/',
          dest: '<%= paths.examples %>/',
          src: '**/*.html',
          expand: true,
          flatten: true,
        }],
      },
    },

    // grunt-contrib-jshint
    jshint: {
      options: {
        jshintrc: true,
      },
      server: [
        'src/*.js',
        'src/**/*.js',
      ],
    },

    // grunt-contrib-stylus
    stylus: {
      compile: {
        options: {
          compress: false,
          paths: [
            'src/examples',
          ],
          import: ['nib', 'nib/vendor'],
          banner: '<%= banner.css %>',
        },

        files: {
          '<%= paths.examples %>/genericBox.css': [
            'src/examples/genericBox/*.styl',
          ]
        },
      },
    },

    // grunt-contrib-uglify
    uglify: {
      options: {
        banner: '<%= banner.js %>',
      },

      lib: {
        options: {
          sourceMap: true,
        },
        files: {
          '<%= paths.lib %>/jquery.genericBox.min.js': [
          'src/lib/jquery.genericBox.js', ]
        },
      }
    },

    // grunt-contrib-watch
    watch: {
      lib: {
        files: ['src/lib/*.js'],
        tasks: ['copy:lib', 'uglify:lib'],
      },

      examples: {
        files: ['src/examples/**/*.html'],
        tasks: ['copy:examples'],
      },

      stylus: {
        files: ['src/**/*.styl'],
        tasks: ['stylus'],
      },
    },

  });

  // find all of the task which start with `grunt-` and load them
  require('matchdep')
    .filterDev(['grunt-*', '!grunt-cli'])
    .forEach(grunt.loadNpmTasks);

  // tasks
  grunt.registerTask(
    'default',
    'Build release',
    [
      'clean:examples',
      'clean:lib',
      'copy:lib',
      'uglify:lib',
      'stylus',
      'copy:examples',
      'watch',
    ]
  );
};


// Export the configuration
module.exports = configure;
